MODEL_3B_DIR = "../../models/qwen2.5-3b-awq/base"
MODEL_7B_DIR = "../../models/qwen2.5-7b-awq/base"
MODEL_7B_NAME = "Qwen/Qwen2.5-7B-Instruct-AWQ"
Conversation_Phase_1_Data_Dir = "../../res/clean_data/conv_phase_1"
Assistant_Chat_Token = "<|im_start|>assistant"
Task_Data_Dir = "../../res/task_data"
Chat_End_Token = "<|im_end|>"
test_dir = "../../models/qwen2.5-7b-awq"
SYS_TEST_PROMPT = ("Your name is 'Abooga'. Your task is to be a helpful LLM-Agent who follows the users instructions. "
                   "Introduce yourself to the user.")
